### PR TITLE
fix(build): update webpack and react-refresh deps

### LINKED ISSUE #13: Got this issue when run this directly after install
C:\projects\webpack5-react-typescript>yarn start
yarn run v1.22.15
$ cross-env WEBPACK_IS_DEV_SERVER=true NODE_ENV=development webpack serve --config webpack.config.babel.js
[webpack-cli] Unable to load '@webpack-cli/serve' command
[webpack-cli] TypeError: options.forEach is not a function
    at WebpackCLI.makeCommand (C:\projects\webpack5-react-typescript\node_modules\webpack-cli\lib\webpack-cli.js:108:21)
    at ServeCommand.apply (C:\projects\webpack5-react-typescript\node_modules\@webpack-cli\serve\lib\index.js:41:19)
    at loadCommandByName (C:\projects\webpack5-react-typescript\node_modules\webpack-cli\lib\webpack-cli.js:626:35)
    at Command.<anonymous> (C:\projects\webpack5-react-typescript\node_modules\webpack-cli\lib\webpack-cli.js:1091:23)
    at Command.listener [as _actionHandler] (C:\projects\webpack5-react-typescript\node_modules\webpack-cli\node_modules\commander\index.js:922:31)
    at Command._parseCommand (C:\projects\webpack5-react-typescript\node_modules\webpack-cli\node_modules\commander\index.js:1503:14)
    at Command.parse (C:\projects\webpack5-react-typescript\node_modules\webpack-cli\node_modules\commander\index.js:1292:10)
    at Command.parseAsync (C:\projects\webpack5-react-typescript\node_modules\webpack-cli\node_modules\commander\index.js:1318:10)
    at WebpackCLI.run (C:\projects\webpack5-react-typescript\node_modules\webpack-cli\lib\webpack-cli.js:1123:28)
    at runCLI (C:\projects\webpack5-react-typescript\node_modules\webpack-cli\lib\bootstrap.js:11:19)
error Command failed with exit code 2.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### PR DESCRIPTION
**Pull request by mod3x**
Hey. I've updated some dependencies to fix #13. Thank you.

### CODE REVIEW

**Comment by mod3x** [comment]
Also #12 not showing up 🙈

**Comment by sankarkumar23** [comment]
Still getting the below even after upgrade. Any insights?


image

**Comment by mod3x** [comment]
> Still getting the below even after upgrade. Any insights?
> 
> image

Hey. Looks like youre using a nodejs version that does not support a [Nullish coalescing operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing_operator). To fix it upgrade nodejs to minimum version 14, [nvm](https://github.com/nvm-sh/nvm) is the easieset way to do so imo

**Comment by mod3x** [comment]
Also @glook looks like a good sign to fill the `engines` settings in `package.json` as nodejs 16 already becomes as LTS
`>=14.0.0 || >=16.0.0` should work just fine

**Pull request merged**
